CREATE TABLE companies(
  symbol VARCHAR(33),
  companyId int ,
  companyIndexId int ,
  country VARCHAR(33),
  sector VARCHAR(55),
  lastScale VARCHAR(55),
  ipoYear VARCHAR(33),
  name VARCHAR(66),
  region VARCHAR(33),
  industry VARCHAR(111),
  marketCap VARCHAR(55),
  adrTso VARCHAR(44),
  exchange VARCHAR(22),
  sumaryQuote VARCHAR(222)
)ENGINE InnoDB;

CREATE TABLE companies_indexes(
  companyIndexId int ,
  companyId int ,
  Ask VARCHAR(33),
  CompanyName VARCHAR(55),
  ExchangeNickName VARCHAR(33),
  AskRealTime DOUBLE,
  Bid DOUBLE,
  BidRealTime DOUBLE,
  BookValue DOUBLE,
  ChangePrecentChange DOUBLE,
  Commission DOUBLE,
  Currency VARCHAR(33),
  ChangeRealTime VARCHAR(33),
  AfterHoursChangeRealTime VARCHAR(33),
  DividentShare DOUBLE,
  LastTradeDate DATE,
  TradeDate DATE,
  EarningShare DOUBLE,
  EPSEstatimateCurrentYear DOUBLE,
  EPSEstatimateNextYear DOUBLE,
  EPSEstatimateNextQuarter DOUBLE,
  DaysLow DOUBLE,
  DaysHighd DOUBLE,
  YearLow DOUBLE,
  YearHigh DOUBLE,
  HoldingsGainPercent DOUBLE,
  AnnualizedGain DOUBLE,
  HoldingsGain DOUBLE,
  HoldingsGainPercentRealTime DOUBLE,
  HoldingsGainRealTime DOUBLE,
  MoreInfo VARCHAR(33),
  OrderBookRealTime VARCHAR(33),
  MarketCapitalization VARCHAR(33),
  MarketCapRealTime DOUBLE,
  EBITDA VARCHAR(44),
  ChangeFormYearLow DOUBLE,
  PercentChangeFormYearLow VARCHAR(33),
  PercebtChangeFromYearHigh VARCHAR(33),
  LastTradeRealTimeWithTime VARCHAR(33),
  ChangePercentRealTime DOUBLE,
  ChangeFromYearHigh DOUBLE,
  LastTradeWithTime VARCHAR(33),
  LastTradePriceOnly DOUBLE,
  HighLimit DOUBLE,
  LowLimit DOUBLE,
  DayRangeMin DOUBLE,
  DayRangeMax DOUBLE,
  DayRangeRealTime VARCHAR(44),
  FiftyDayMovingAverage DOUBLE,
  TwoHoundreddayMovingAverage DOUBLE,
  ChangeFromTwoHoundreddayMovingAverage VARCHAR(44),
  PercentChangeFormFiftydayMovingAverage VARCHAR(44),
  Notes VARCHAR(44),
  Open DOUBLE,
  PreviosClosed DOUBLE,
  PricePaid DOUBLE,
  ChangeningPercent VARCHAR(33),
  PriceSales DOUBLE,
  PriceBook DOUBLE,
  ExDividenDate VARCHAR(33),
  PERation VARCHAR(33),
  DividenPayDate VARCHAR(33),
  PeRationRealTime VARCHAR(33),
  PEGRation DOUBLE,
  PriceEPSEstamateCurrentYear DOUBLE,
  Symbol VARCHAR(22),
  SharesOwned DOUBLE,
  SortRation DOUBLE,
  LastTradeTime VARCHAR(33),
  TickerTrend VARCHAR(33),
  OneyrTargetPrice DOUBLE,
  HoldingValues VARCHAR(33),
  HoldingsValueRealTime VARCHAR(33),
  YearRangeMin DOUBLE,
  YearRangeMax DOUBLE,
  DaysValueChnage VARCHAR(33),
  DaysValueChangeRealTime VARCHAR(33),
  StockExchange VARCHAR(33),
  PercentChange VARCHAR(33),
  Changee VARCHAR(33)
)ENGINE InnoDB;



ALTER TABLE companies MODIFY companyId int AUTO_INCREMENT PRIMARY KEY ;
ALTER TABLE companies MODIFY companyIndexId int not null UNIQUE;
ALTER TABLE companies add FOREIGN KEY (companyIndexId) REFERENCES companies_indexes(companyIndexId);

ALTER TABLE companies_indexes MODIFY companyId int AUTO_INCREMENT PRIMARY KEY ;
ALTER TABLE companies_indexes MODIFY companyIndexId int not null UNIQUE;
ALTER TABLE companies_indexes add FOREIGN KEY (companyIndexId) REFERENCES companies(companyIndexId);

